import { MigrationInterface, QueryRunner } from 'typeorm';

export class BackfillInventoryMovements1700000000006
  implements MigrationInterface
{
  name = 'BackfillInventoryMovements1700000000006';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Note: The enum type name is auto-generated by TypeORM as inventory_movements_type_enum
    // based on the table_name + _ + column_name + _enum pattern.

    // 1. Backfill from inventory_batches — Purchase Orders
    await queryRunner.query(`
      INSERT INTO inventory_movements (id, product_id, user_id, type, quantity, origin, destination, reference_type, reference_id, metadata, created_at)
      SELECT
        gen_random_uuid(),
        ib.product_id,
        ib.user_id,
        'In'::inventory_movements_type_enum,
        ib.initial_quantity,
        'Proveedor (Compra)',
        'Almacén Principal',
        'PURCHASE_ORDER',
        ib.purchase_order_id,
        jsonb_build_object('purchasePrice', ib.purchase_price, 'adjustmentReason', ib.adjustment_reason),
        ib.created_at
      FROM inventory_batches ib
      WHERE ib.purchase_order_id IS NOT NULL
        AND ib.initial_quantity > 0
    `);

    // 2. Backfill from inventory_batches — Initial Stock
    await queryRunner.query(`
      INSERT INTO inventory_movements (id, product_id, user_id, type, quantity, origin, destination, reference_type, reference_id, metadata, created_at)
      SELECT
        gen_random_uuid(),
        ib.product_id,
        ib.user_id,
        'In'::inventory_movements_type_enum,
        ib.initial_quantity,
        'Stock Inicial',
        'Almacén Principal',
        'INITIAL_STOCK',
        NULL,
        jsonb_build_object('purchasePrice', ib.purchase_price, 'adjustmentReason', ib.adjustment_reason),
        ib.created_at
      FROM inventory_batches ib
      WHERE ib.purchase_order_id IS NULL
        AND ib.adjustment_reason = 'Stock Inicial'
        AND ib.initial_quantity > 0
    `);

    // 3. Backfill from inventory_batches — Manual Adjustments (positive)
    await queryRunner.query(`
      INSERT INTO inventory_movements (id, product_id, user_id, type, quantity, origin, destination, reference_type, reference_id, metadata, created_at)
      SELECT
        gen_random_uuid(),
        ib.product_id,
        ib.user_id,
        'In'::inventory_movements_type_enum,
        ib.initial_quantity,
        'Ajuste de inventario',
        'Ajuste de inventario',
        'MANUAL_ADJUSTMENT',
        NULL,
        jsonb_build_object('purchasePrice', ib.purchase_price, 'adjustmentReason', ib.adjustment_reason),
        ib.created_at
      FROM inventory_batches ib
      WHERE ib.purchase_order_id IS NULL
        AND (ib.adjustment_reason IS NULL OR ib.adjustment_reason != 'Stock Inicial')
        AND ib.initial_quantity > 0
    `);

    // 4. Backfill from inventory_batches — Manual Adjustments (negative / Out)
    await queryRunner.query(`
      INSERT INTO inventory_movements (id, product_id, user_id, type, quantity, origin, destination, reference_type, reference_id, metadata, created_at)
      SELECT
        gen_random_uuid(),
        ib.product_id,
        ib.user_id,
        'Out'::inventory_movements_type_enum,
        ABS(ib.initial_quantity),
        'Ajuste de inventario',
        'Ajuste de inventario',
        'MANUAL_ADJUSTMENT',
        NULL,
        jsonb_build_object('purchasePrice', ib.purchase_price, 'adjustmentReason', ib.adjustment_reason),
        ib.created_at
      FROM inventory_batches ib
      WHERE ib.purchase_order_id IS NULL
        AND ib.initial_quantity < 0
    `);

    // 5. Backfill from invoice_items + invoices — Sales
    await queryRunner.query(`
      INSERT INTO inventory_movements (id, product_id, user_id, type, quantity, origin, destination, reference_type, reference_id, metadata, created_at)
      SELECT
        gen_random_uuid(),
        ii.product_id,
        NULL,
        'Out'::inventory_movements_type_enum,
        ii.quantity,
        'Almacén Principal',
        'Cliente Final',
        'SALES_INVOICE',
        i.id::text,
        NULL,
        COALESCE(i.date, i.created_at)
      FROM invoice_items ii
      INNER JOIN invoices i ON i.id = ii.invoice_id
    `);

    // 6. Backfill from credit_note_items + credit_notes WHERE restored = true
    await queryRunner.query(`
      INSERT INTO inventory_movements (id, product_id, user_id, type, quantity, origin, destination, reference_type, reference_id, metadata, created_at)
      SELECT
        gen_random_uuid(),
        cni.product_id,
        NULL,
        'In'::inventory_movements_type_enum,
        cni.quantity,
        'Cliente Final (Devolución)',
        'Almacén Principal',
        'CREDIT_NOTE',
        cn.id::text,
        NULL,
        COALESCE(cn.created_at, NOW())
      FROM credit_note_items cni
      INNER JOIN credit_notes cn ON cn.id = cni.credit_note_id
      WHERE cni.restored = true
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Remove all backfilled data (keep records created by the new recording points)
    await queryRunner.query(`DELETE FROM inventory_movements`);
  }
}
