import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddSequentialNumberAndEmissionTable1750000000002
  implements MigrationInterface
{
  name = 'AddSequentialNumberAndEmissionTable1750000000002';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // 1. Add sequential_number as identity column
    await queryRunner.query(
      `ALTER TABLE "invoices" ADD COLUMN "sequential_number" INT GENERATED BY DEFAULT AS IDENTITY`,
    );

    // 2. Create invoice_electronic_emissions table
    await queryRunner.query(
      `CREATE TABLE "invoice_electronic_emissions" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "invoice_id" uuid,
        "number" varchar NOT NULL,
        "cude" varchar NULL,
        "qr_url" varchar NULL,
        "public_url" varchar NULL,
        "is_validated" boolean NOT NULL DEFAULT false,
        "validated_at" TIMESTAMP NULL,
        "numbering_range" jsonb NULL,
        "items" jsonb NULL,
        "taxes" jsonb NULL,
        "totals" jsonb NULL,
        "links" jsonb NULL,
        "created_at" TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "PK_invoice_electronic_emissions" PRIMARY KEY ("id")
      )`,
    );

    // 3. Add FK constraint
    await queryRunner.query(
      `ALTER TABLE "invoice_electronic_emissions"
        ADD CONSTRAINT "FK_invoice_electronic_emissions_invoice"
        FOREIGN KEY ("invoice_id")
        REFERENCES "invoices"("id")
        ON DELETE CASCADE`,
    );

    // 4. Create unique index on invoice_id
    await queryRunner.query(
      `CREATE UNIQUE INDEX "REL_invoice_electronic_emissions_invoice"
        ON "invoice_electronic_emissions" ("invoice_id")`,
    );

    // 5. Migrate existing factus_number data to emission table
    await queryRunner.query(
      `INSERT INTO "invoice_electronic_emissions" ("invoice_id", "number")
        SELECT "id", "factus_number"
        FROM "invoices"
        WHERE "factus_number" IS NOT NULL`,
    );

    // 6. Drop factus_number column
    await queryRunner.query(
      `ALTER TABLE "invoices" DROP COLUMN "factus_number"`,
    );

    // 7. Make invoice_number nullable and drop unique constraint
    await queryRunner.query(
      `ALTER TABLE "invoices" ALTER COLUMN "invoice_number" DROP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "invoices" DROP CONSTRAINT IF EXISTS "UQ_invoices_invoice_number"`,
    );

    // 8. Drop unique index on invoice_number if exists
    await queryRunner.query(
      `DROP INDEX IF EXISTS "IDX_invoices_invoice_number"`,
    );

    // 9. Seed sequence to next value after existing max
    await queryRunner.query(
      `SELECT setval(
        pg_get_serial_sequence('invoices', 'sequential_number'),
        COALESCE((SELECT MAX(sequential_number) FROM "invoices"), 0)
      )`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Reverse order
    await queryRunner.query(
      `ALTER TABLE "invoices" ADD COLUMN "factus_number" varchar NULL`,
    );

    // Restore factus_number from emission table
    await queryRunner.query(
      `UPDATE "invoices" SET "factus_number" = (
        SELECT "number" FROM "invoice_electronic_emissions"
        WHERE "invoice_electronic_emissions"."invoice_id" = "invoices"."id"
        LIMIT 1
      )`,
    );

    await queryRunner.query(
      `ALTER TABLE "invoices" ALTER COLUMN "invoice_number" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "invoices" ADD CONSTRAINT "UQ_invoices_invoice_number" UNIQUE ("invoice_number")`,
    );

    await queryRunner.query(
      `DROP TABLE IF EXISTS "invoice_electronic_emissions"`,
    );

    await queryRunner.query(
      `ALTER TABLE "invoices" DROP COLUMN "sequential_number"`,
    );
  }
}
